@URL = http://localhost:5287

@TOKEN = eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJIb3J0ZW5jaWEiLCJlbWFpbCI6ImZsb3IxQGVtYWlsLmNvbSIsImp0aSI6IjUiLCJuYW1laWQiOiI1IiwibmJmIjoxNzExMzIxODM3LCJleHAiOjE3MTEzMjkwMzcsImlhdCI6MTcxMTMyMTgzNywiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo1Mjg3IiwiYXVkIjoiaHR0cDovL2xvY2FsaG9zdDo1Mjg3In0.4IvomZX1R4rhyD4wCLTZaq-dFtWXqg6HT94zkA3PF7sjyCP5tjgGiWKD2noZJ2N2Ik88huFufZZ9VzVHyyPROg



###
POST {{URL}}/v1/customer/register
content-type: application/json

{
  "nome": "dog1",
  "email": "dog1@email.com",
  "telefone": "12341234",
  "tipoCliente": "PF",
  "senhaLogin": "string"
}

###



###
POST {{URL}}/v1/customer/login
content-type: application/json

{
  "email": "flor1@email.com",
  "password": "string"
}
###


###
GET {{URL}}/v1/account/customer
Authorization: Bearer {{TOKEN}}

###


###
GET {{URL}}/v1/account/account
Authorization: Bearer {{TOKEN}}

###

###
GET {{URL}}/v1/account/balance
Authorization: Bearer {{TOKEN}}

###


###
GET {{URL}}/v1/usuario/17
Authorization: Bearer {{TOKEN}}
Accept: application/json

###



###
GET {{URL}}/v1/usuario/logado
Authorization: Bearer {{TOKEN}}

###



###
POST {{URL}}/v1/customer/addressregister
content-type: application/json

{
  "id": 0,
  "CustomerId": 1,
  "rua": "string",
  "cidade": "string",
  "estado": "string",
  "cep": "string",
  "pais": "string",
  "criadoEm": "2024-03-24T00:39:28.521Z",
  "atualizadoEm": "2024-03-24T00:39:28.521Z",
  "deletadoEm": "2024-03-24T00:39:28.521Z"
}

###



###
POST {{URL}}/v1/customer/registracontapj
content-type: application/json

{
  "customerRequest": {
    "name": "Hortencia",
    "email": "flor1@email.com",
    "phone": "string",
    "clientType": "PF",
    "loginPassword": "string"
  },
  "addressRequest": {
    "street": "Rua das Flores",
    "city": "string",
    "state": "string",
    "zipCode": "string",
    "country": "string",
    "createdAt": "2024-03-24T21:44:24.500Z",
    "updatedAt": "2024-03-24T21:44:24.500Z",
    "deletedAt": "2024-03-24T21:44:24.500Z"
  },
  "legalEntityRequest": {
    "cnpj": "18760000",
    "fantasyName": "string",
    "stateRegistration": "string",
    "annualBillingInCents": 1099000,
    "taxation": "string"
  },
  "accountRequest": {
    "accountType": 0,
    "keyPix": "pix2345234",
    "passwordTransaction": "string",
    "confirmPasswordTransaction": "string"
  }
}
###