@URL = http://localhost:5216

@TOKEN = eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJ0aGVMb2dhZG9nIiwiZW1haWwiOiJkb2dAZW1haWwuY29tIiwianRpIjoiYTJlYTUzNGItNGVlZS00OTVkLTg0N2MtMmIyMDA1YjQ0MjVjIiwibmJmIjoxNzExMDk1MzEyLCJleHAiOjE3MTExMDI1MTIsImlhdCI6MTcxMTA5NTMxMiwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo1MjE2IiwiYXVkIjoiaHR0cDovL2xvY2FsaG9zdDo1MjE2In0.mZFBN8BIU3mWwec-DI792UQJjqxQQuS5k1JzCB5DCEhawun73ei4tiAueoQuVZetNv9Jv_PteYPKml7NENpCcg



###
POST {{URL}}/v1/usuario/cadastro
content-type: application/json

{
  "nome": "teget2",
  "email": "tegete2@email.com",
  "telefone": "124432333",
  "tipoCliente": "PJ",
  "senhaLogin": "string"
}

###



###
POST {{URL}}/v1/usuario/login
content-type: application/json

{
  "email": "dog@email.com",
  "senha": "string"
}
###



###
GET {{URL}}/v1/usuario/17
Authorization: Bearer {{TOKEN}}
Accept: application/json

###



###
GET {{URL}}/v1/usuario/logado
Authorization: Bearer {{TOKEN}}

###




